//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RuralCafe.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000000")]
        public int DEFAULT_QUOTA {
            get {
                return ((int)(this["DEFAULT_QUOTA"]));
            }
            set {
                this["DEFAULT_QUOTA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int DEFAULT_DEPTH {
            get {
                return ((int)(this["DEFAULT_DEPTH"]));
            }
            set {
                this["DEFAULT_DEPTH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::RuralCafe.RequestHandler.Richness DEFAULT_RICHNESS {
            get {
                return ((global::RuralCafe.RequestHandler.Richness)(this["DEFAULT_RICHNESS"]));
            }
            set {
                this["DEFAULT_RICHNESS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("INFO")]
        public global::RuralCafe.LogLevel LOGLEVEL {
            get {
                return ((global::RuralCafe.LogLevel)(this["LOGLEVEL"]));
            }
            set {
                this["LOGLEVEL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("604800")]
        public int DNS_CACHE_TTL {
            get {
                return ((int)(this["DNS_CACHE_TTL"]));
            }
            set {
                this["DNS_CACHE_TTL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FORCE_LOGIN {
            get {
                return ((bool)(this["FORCE_LOGIN"]));
            }
            set {
                this["FORCE_LOGIN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SHOW_SURVEY {
            get {
                return ((bool)(this["SHOW_SURVEY"]));
            }
            set {
                this["SHOW_SURVEY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool USE_ONTOLOGY {
            get {
                return ((bool)(this["USE_ONTOLOGY"]));
            }
            set {
                this["USE_ONTOLOGY"] = value;
            }
        }
    }
}
