//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RuralCafe.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Files : global::System.Configuration.ApplicationSettingsBase {
        
        private static Files defaultInstance = ((Files)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Files())));
        
        public static Files Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\RuralCafe")]
        public string BASE_DIR {
            get {
                return ((string)(this["BASE_DIR"]));
            }
            set {
                this["BASE_DIR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("files-computer_studies")]
        public string LOCAL_CACHE_PATH {
            get {
                return ((string)(this["LOCAL_CACHE_PATH"]));
            }
            set {
                this["LOCAL_CACHE_PATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cache")]
        public string REMOTE_CACHE_PATH {
            get {
                return ((string)(this["REMOTE_CACHE_PATH"]));
            }
            set {
                this["REMOTE_CACHE_PATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("index-computer_studies")]
        public string LOCAL_INDEX_PATH {
            get {
                return ((string)(this["LOCAL_INDEX_PATH"]));
            }
            set {
                this["LOCAL_INDEX_PATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LOCAL_WIKI_DUMP_FILE {
            get {
                return ((string)(this["LOCAL_WIKI_DUMP_FILE"]));
            }
            set {
                this["LOCAL_WIKI_DUMP_FILE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("trotro.html")]
        public string DEFAULT_SEARCH_PAGE {
            get {
                return ((string)(this["DEFAULT_SEARCH_PAGE"]));
            }
            set {
                this["DEFAULT_SEARCH_PAGE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LOCAL_MAX_CACHE_SIZE_MIB {
            get {
                return ((int)(this["LOCAL_MAX_CACHE_SIZE_MIB"]));
            }
            set {
                this["LOCAL_MAX_CACHE_SIZE_MIB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int REMOTE_MAX_CACHE_SIZE_MIB {
            get {
                return ((int)(this["REMOTE_MAX_CACHE_SIZE_MIB"]));
            }
            set {
                this["REMOTE_MAX_CACHE_SIZE_MIB"] = value;
            }
        }
    }
}
