//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RuralCafe.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Network : global::System.Configuration.ApplicationSettingsBase {
        
        private static Network defaultInstance = ((Network)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Network())));
        
        public static Network Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int MIN_MAX_INFLIGHT_REQUESTS {
            get {
                return ((int)(this["MIN_MAX_INFLIGHT_REQUESTS"]));
            }
            set {
                this["MIN_MAX_INFLIGHT_REQUESTS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5120")]
        public int MIN_BYTES_PER_SECOND_PER_REQUEST {
            get {
                return ((int)(this["MIN_BYTES_PER_SECOND_PER_REQUEST"]));
            }
            set {
                this["MIN_BYTES_PER_SECOND_PER_REQUEST"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10240")]
        public int BYTES_PER_SECOND_ONLINE_THRESHOLD {
            get {
                return ((int)(this["BYTES_PER_SECOND_ONLINE_THRESHOLD"]));
            }
            set {
                this["BYTES_PER_SECOND_ONLINE_THRESHOLD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FLUCTUATE_MAX_REQUESTS {
            get {
                return ((bool)(this["FLUCTUATE_MAX_REQUESTS"]));
            }
            set {
                this["FLUCTUATE_MAX_REQUESTS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int LOCAL_MAX_INFLIGHT_REQUESTS {
            get {
                return ((int)(this["LOCAL_MAX_INFLIGHT_REQUESTS"]));
            }
            set {
                this["LOCAL_MAX_INFLIGHT_REQUESTS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int REMOTE_MAX_INFLIGHT_REQUESTS {
            get {
                return ((int)(this["REMOTE_MAX_INFLIGHT_REQUESTS"]));
            }
            set {
                this["REMOTE_MAX_INFLIGHT_REQUESTS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DETECT_NETWORK_AUTO {
            get {
                return ((bool)(this["DETECT_NETWORK_AUTO"]));
            }
            set {
                this["DETECT_NETWORK_AUTO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Slow")]
        public global::RuralCafe.RCLocalProxy.NetworkStatusCode NETWORK_STATUS {
            get {
                return ((global::RuralCafe.RCLocalProxy.NetworkStatusCode)(this["NETWORK_STATUS"]));
            }
            set {
                this["NETWORK_STATUS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000000")]
        public int MAXIMUM_DOWNLOAD_SPEED {
            get {
                return ((int)(this["MAXIMUM_DOWNLOAD_SPEED"]));
            }
            set {
                this["MAXIMUM_DOWNLOAD_SPEED"] = value;
            }
        }
    }
}
