//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RuralCafe.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class GlobalCacheRCData
    {
        public string httpMethod { get; set; }
        public string url { get; set; }
        public System.DateTime downloadTime { get; set; }
        public System.DateTime lastRequestTime { get; set; }
        public int numberOfRequests { get; set; }
    }
}
