//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RuralCafe.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1")]
        public string LOCAL_PROXY_IP_ADDRESS {
            get {
                return ((string)(this["LOCAL_PROXY_IP_ADDRESS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8080")]
        public int LOCAL_PROXY_LISTEN_PORT {
            get {
                return ((int)(this["LOCAL_PROXY_LISTEN_PORT"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1")]
        public string REMOTE_PROXY_IP_ADDRESS {
            get {
                return ((string)(this["REMOTE_PROXY_IP_ADDRESS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8081")]
        public int REMOTE_PROXY_LISTEN_PORT {
            get {
                return ((int)(this["REMOTE_PROXY_LISTEN_PORT"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Slow")]
        public global::RuralCafe.RCProxy.NetworkStatusCode NETWORK_STATUS {
            get {
                return ((global::RuralCafe.RCProxy.NetworkStatusCode)(this["NETWORK_STATUS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EXTERNAL_PROXY_IP_ADDRESS {
            get {
                return ((string)(this["EXTERNAL_PROXY_IP_ADDRESS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int EXTERNAL_PROXY_LISTEN_PORT {
            get {
                return ((int)(this["EXTERNAL_PROXY_LISTEN_PORT"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EXTERNAL_PROXY_LOGIN {
            get {
                return ((string)(this["EXTERNAL_PROXY_LOGIN"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EXTERNAL_PROXY_PASS {
            get {
                return ((string)(this["EXTERNAL_PROXY_PASS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("trotro.html")]
        public string DEFAULT_SEARCH_PAGE {
            get {
                return ((string)(this["DEFAULT_SEARCH_PAGE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000000")]
        public int DEFAULT_QUOTA {
            get {
                return ((int)(this["DEFAULT_QUOTA"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int DEFAULT_DEPTH {
            get {
                return ((int)(this["DEFAULT_DEPTH"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::RuralCafe.RequestHandler.Richness DEFAULT_RICHNESS {
            get {
                return ((global::RuralCafe.RequestHandler.Richness)(this["DEFAULT_RICHNESS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000000")]
        public int MAXIMUM_DOWNLOAD_SPEED {
            get {
                return ((int)(this["MAXIMUM_DOWNLOAD_SPEED"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("index-computer_studies-test")]
        public string INDEX_PATH {
            get {
                return ((string)(this["INDEX_PATH"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("files-computer_studies-test")]
        public string LOCAL_CACHE_PATH {
            get {
                return ((string)(this["LOCAL_CACHE_PATH"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cache")]
        public string REMOTE_CACHE_PATH {
            get {
                return ((string)(this["REMOTE_CACHE_PATH"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WIKI_DUMP_DIR {
            get {
                return ((string)(this["WIKI_DUMP_DIR"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WIKI_DUMP_FILE {
            get {
                return ((string)(this["WIKI_DUMP_FILE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int LOCAL_MAXIMUM_ACTIVE_REQUESTS {
            get {
                return ((int)(this["LOCAL_MAXIMUM_ACTIVE_REQUESTS"]));
            }
        }
    }
}
