//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RuralCafe.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class GlobalCacheItem
    {
        public string httpMethod { get; set; }
        public string url { get; set; }
        public string responseHeaders { get; set; }
        public string filename { get; set; }
        public short statusCode { get; set; }
    }
}
