//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RuralCafe.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RCDatabaseEntities : DbContext
    {
        public RCDatabaseEntities()
            : base("name=RCDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<GlobalCacheItem> GlobalCacheItem { get; set; }
        public DbSet<GlobalCacheRCData> GlobalCacheRCData { get; set; }
    }
}
